version: "3.8"

services:
  database:
    image: postgres:13
    restart: always
    hostname: ${POSTGRES_HOSTNAME}
    env_file:
      - ../.env
    volumes:
      - data:/var/lib/postgresql/data/
    profiles:
      - db

  app:
    image: blog_app:${IMAGE_VERSION}
    build:
      context: ../
      dockerfile: .deploy/Dockerfile
    env_file:
      - ../.env
    depends_on:
      - database
    ports:
      - ${APP_PORT}:5000
    profiles:
      - app


volumes:
  data: